# Generated by Django 2.2 on 2020-12-16 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Day')),
                ('sleep_at', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 22, 0), help_text='Your last night sleep time & Forget about Dates.', verbose_name='Sleep At')),
                ('arise_at', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 4, 0), verbose_name='Wake Up At ')),
                ('noon_sleep', models.BooleanField(default=False)),
                ('noon_sleep_at', models.DateTimeField(blank=True, null=True, verbose_name='Noon Sleeps At ')),
                ('noon_arise_at', models.DateTimeField(blank=True, null=True, verbose_name='Noon Wakeup At ')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
