# Generated by Django 2.2 on 2020-12-16 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleep_manage_app', '0002_auto_20201216_2153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sleep',
            unique_together={('user_name', 'your_date')},
        ),
    ]
