# Generated by Django 2.2 on 2020-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_manage_app', '0003_auto_20201216_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='arise_at',
            field=models.DateTimeField(verbose_name='Wake Up At '),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_at',
            field=models.DateTimeField(help_text='Your last night sleep time & Forget about Dates.', verbose_name='Sleep At'),
        ),
    ]
