# Generated by Django 2.2 on 2020-12-18 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_manage_app', '0004_auto_20201218_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='your_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 13, 50, 48, 923853, tzinfo=utc), verbose_name='Day'),
        ),
    ]
