# Generated by Django 2.2 on 2020-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_manage_app', '0008_auto_20201218_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='arise_at',
            field=models.DateTimeField(verbose_name='Wake Up At'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='noon_arise_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Noon Wakeup At'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='noon_sleep_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Noon Sleeps At'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_at',
            field=models.DateTimeField(help_text='Your last night sleep time.', verbose_name='Sleep At'),
        ),
    ]
